version: '3.1'
services:
  stats-server:
    build: stats-service
    image: stats-service
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6540:5431"
    environment:
      - POSTGRES_DB=jdbc:h2:mem:stats-service
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: core-db
    ports:
        - "6541:5432"
    environment:
        - POSTGRES_DB=jdbc:h2:mem:ewm-service
        - POSTGRES_USER=ewm
        - POSTGRES_PASSWORD=ewm
